#!/bin/bash
MY_PATH="`dirname \"$0\"`"
cd "$MY_PATH"
HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="Creado por: Elsoberanox - https://www.youtube.com/c/ElsoberanoxLinux"
TITLE="www.juegosenlinux.site"
MENU="The Simpsons Hit & Run - Elsoberanox"

OPTIONS=(1 "Instalar TSHR"
         2 "Desinstalar"
         3 "Ver mas ports"
         4 "Salir")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
#!/bin/bash
MY_PATH="`dirname \"$0\"`"
cd "$MY_PATH"
sudo rm -R /usr/bin/winetricks
sudo rm -R /opt/wineson
sudo chmod +x winetricks
sudo cp winetricks /usr/bin/
sudo chmod +x badown
wget https://archive.org/download/wineson.7z_202110/wineson.7z
7z x wineson.7z 
sudo rm -R wineson.7z
sudo mv wineson /opt/
./badown https://www.mediafire.com/file/7v06f5c19780rkm/TSHR.7z
7z x TSHR.7z
sudo rm -R TSHR.7z
mkdir $HOME/Juegos/
mkdir $HOME/Juegos/TSHR/
cd TSHR
export WINEPREFIX=$HOME/Juegos/TSHR/
export PATH=/opt/wineson/bin/:/usr/bin/
wine setup.exe
cd ..
sudo rm -R TSHR
echo -e "cd $HOME/Juegos/TSHR/drive_c/Games/The\ Simpsons\ Hit\ and\ Run/\nexport PATH=/opt/wineson/bin/\nwine Simpsons.exe" >> TSHR-bin
sudo chmod +x TSHR-bin
sudo mv TSHR-bin /usr/bin/


wget https://archive.org/download/tshricon/tshricon.png
sudo mv tshricon.png /opt/
echo -e "[Desktop Entry]\n Version=1.0\n Type=Application\n Name=The Simpsons Hit & Run\n Comment=TSHR-bin\n Icon=/opt/tshricon.png\n Exec=TSHR-bin\n Categories=Game;" >> TSHR.desktop
sudo chmod +x TSHR.desktop
sudo mv TSHR.desktop $HOME/.local/share/applications
xdg-desktop-menu forceupdate


            ;;
        2)
sudo rm -R /usr/bin/winetricks
sudo rm -R /opt/wineson
sudo rm -R /usr/bin/TSHR-bin
sudo rm -R /opt/tshricon.png
sudo rm -R $HOME/Juegos/TSHR/
sudo rm -R $HOME/.local/share/applications/TSHR.desktop
xdg-desktop-menu forceupdate

            ;;
        3)
            xdg-open https://www.juegosenlinux.site/
            ;;
            
                    3)
            exit
            ;;
esac
